[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
unallowed = [
    "GPL-2.0",
    "GPL-3.0",
]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
]
