[package]
name = "parallel-jit"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
parking_lot = "0.12"
vm-executors = { path = "../vm-executors" }
tiered-compiler = { path = "../tiered-compiler" }

[dev-dependencies]
