[package]
name = "parallel-jit"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
parking_lot = "0.12"
vm-runtime = { path = "../vm-runtime" }
# async-executor 已合并到 vm-runtime
tiered-compiler = { path = "../tiered-compiler" }

[dev-dependencies]
