[package]
name = "vm-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
thiserror = "2.0"
log = "0.4"
async-trait = "0.1"
rand = "0.9"

[dev-dependencies]
tokio = { version = "1.48", features = ["full"] }
