[package]
name = "vm-graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
vm-core = { path = "../vm-core" }
log = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
