apiVersion: v1
kind: Service
metadata:
  name: vm-service
  labels:
    app: vm-service
spec:
  type: ClusterIP
  selector:
    app: vm-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http