[package]
name = "perf-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
async-executor = { path = "../async-executor" }
coroutine-scheduler = { path = "../coroutine-scheduler" }

[dev-dependencies]
