[package]
name = "vm-osal"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.17"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Memory", "Win32_System_Threading"] }
