[package]
name = "vm-osal"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = { workspace = true }
vm-core = { path = "../vm-core" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Memory", "Win32_System_Threading"] }
