[package]
name = "async-executor"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12"
vm-engine-jit = { path = "../vm-engine-jit" }

[dev-dependencies]
tokio = { version = "1.48", features = ["rt", "macros"] }
