[package]
name = "fibonacci"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
vm-core = { path = "../../vm-core" }
vm-engine = { path = "../../vm-engine", features = ["jit", "interpreter"] }
vm-mem = { path = "../../vm-mem" }
vm-frontend = { path = "../../vm-frontend" }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
