[package]
name = "tiered-compiler"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
parking_lot = "0.12"
vm-engine = { path = "../vm-engine", features = ["executor"] }

[dev-dependencies]
